### ISSUE TITLE
NullPointerException on shutdown.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#105]
CrateReloaded v1.3.85
Paper dev 1043 (Spigot 1.11.2)

Shut down my server to update and restart it. This NPE occurred during the shutdown procedure.

```
[12:38:37] [Server thread/INFO]: [CrateReloaded] Disabling CrateReloaded v1.3.85
[12:38:37] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v1.3.85 (Is it up to date?)
java.lang.NullPointerException
	at cratereloaded.bp.close(Logger.java:48) ~[?:?]
	at cratereloaded.b.cleanup(CrateReloaded.java:133) ~[?:?]
	at cratereloaded.b.onDisable(CrateReloaded.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1043]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1043]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.11.2.jar:git-Paper-1043]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.11.2.jar:git-Paper-1043]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:347) [patched_1.11.2.jar:git-Paper-1043]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:477) [patched_1.11.2.jar:git-Paper-1043]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:684) [patched_1.11.2.jar:git-Paper-1043]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by imWillX** [comment]
Thanks, will fix it by end of this weekend.

**Comment by mibby** [comment]
All good, take your time with the update. :) I've been busy myself with work so haven't really had much time  for debugging.

**Comment by mibby** [comment]
Any update? Seems to occur on shutdown regardless if someone is using a crate or not.

```
[08:00:00] [Server thread/INFO]: [CrateReloaded] Disabling CrateReloaded v1.3.85
[08:00:00] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v1.3.85 (Is it up to date?)
java.lang.NullPointerException
	at cratereloaded.bp.close(Logger.java:48) ~[?:?]
	at cratereloaded.b.cleanup(CrateReloaded.java:133) ~[?:?]
	at cratereloaded.b.onDisable(CrateReloaded.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1052]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1052]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.11.2.jar:git-Paper-1052]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.11.2.jar:git-Paper-1052]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:347) [patched_1.11.2.jar:git-Paper-1052]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:481) [patched_1.11.2.jar:git-Paper-1052]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:688) [patched_1.11.2.jar:git-Paper-1052]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by imWillX** [comment]
It's a small issue with the logger shutting down. It's a minor nuisance with nothing major. 

I'll definitely fix it this weekend.

**Comment by imWillX** [comment]
Fixed. Will be released by Sunday.
