### ISSUE TITLE
/crate set broken in 1.12.1

### ISSUE THREAD

**Issue by XXLuigiMario** [imWillX/CrateReloaded#142]
I get this error when running /crate set on Spigot 1.12.1 using CrateReloaded 1.3.97.2:

> [15:49:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'crate' in plugin CrateReloaded v1.3.97.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at cratereloaded.bn.w(Camera.java:23) ~[?:?]
	at cratereloaded.E.a(Set.java:39) ~[?:?]
	at cratereloaded.j.onCommand(CommandManager.java:118) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.1.jar:git-Spigot-edd0396-20ab5d3]
	... 15 more

**Comment by imWillX** [comment]
Fixed in 1.3.97.3
