### ISSUE TITLE
IndexOutOfBoundsException: Index: 54, Size: 46

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#53]
CrateReloaded 1.3.70
PaperSpigot dev 706
ProtocolLib dev 273
PermissionsEx 1.23.5-SNAPSHOT

This error occurs when in creative, opening a chest, and right clicking the key in your inventory, with creative-control enabled. Left clicking and middle clicking is fine. Only errors on right click.

```
[00:38:54] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_92]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1938) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-706]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-706]
	... 5 more
[00:38:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_92]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.Container.getSlot(Container.java:109) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1938) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.2.jar:git-Paper-706]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[patched_1.9.2.jar:git-Paper-706]
	... 5 more
```

**Comment by imWillX** [comment]
Issue appears to be fixed as of latest (private) experimental build.

**Comment by mibby** [comment]
Issue not fixed.
```
[12:32:32] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:46) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-748]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_92]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.Container.getSlot(Container.java:111) ~[patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1937) ~[patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.9.4.jar:git-Paper-748]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.9.4.jar:git-Paper-748]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) ~[patched_1.9.4.jar:git-Paper-748]
	... 5 more
```

**Comment by imWillX** [comment]
Hey Mibby, 

Can you post your crate.yml?

**Comment by imWillX** [comment]
Fixed as of latest experimental. Confirmed this time.
