### ISSUE TITLE
Sound effects no longer play - CrateReloaded is interpreting them as particle effects that do not exist.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#64]
Spigot 1.10
CrateReloaded Premium 1.3.73

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html

```
[18:26:22] [Server thread/ERROR]: [CrateReloaded] A particle effect with this name doesn't exist! FIREWORK
[18:26:22] [Server thread/ERROR]: [CrateReloaded] A particle effect with this name doesn't exist! ENTITY_GENERIC_DRINK
[18:26:22] [Craft Scheduler Thread - 127/ERROR]: [CrateReloaded] A particle effect with this name doesn't exist! UI_BUTTON_CLICK
[18:27:04] [Server thread/ERROR]: [CrateReloaded] A particle effect with this name doesn't exist! ENTITY_BAT_TAKEOFF
```

Working fine in 1.3.69.

**Comment by mibby** [comment]
IndexOutOfBoundsException hopefully related to the particle issue. If not, new ticket may be needed. Had it spam 131 times in a few hours.

```
[18:26:23] [Craft Scheduler Thread - 134/WARN]: Exception in thread "Craft Scheduler Thread - 134" 
[18:26:23] [Craft Scheduler Thread - 134/WARN]: org.apache.commons.lang.UnhandledException: Plugin CrateReloaded v1.3.73 generated an exception while executing task 370027
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at cratereloaded.S.a(CSGOMenu.java:195)
	at cratereloaded.S.a(CSGOMenu.java:112)
	at cratereloaded.W.a(CSGOTask.java:87)
	at cratereloaded.W.b(CSGOTask.java:11)
	at cratereloaded.X.run(CSGOTask.java:52)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**Comment by imWillX** [comment]
Fixed, will be released in next update.
