### ISSUE TITLE
IndexOutOfBoundsException on CSGO crate rotation spin.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#65]
Spigot 1.10
CrateReloaded Premium 1.3.73

Error spams throughout the rotation of a CSGO crate.

```
[18:26:22] [Craft Scheduler Thread - 127/WARN]: Exception in thread "Craft Scheduler Thread - 127" 
[18:26:22] [Craft Scheduler Thread - 127/WARN]: org.apache.commons.lang.UnhandledException: Plugin CrateReloaded v1.3.73 generated an exception while executing task 370027
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at cratereloaded.S.a(CSGOMenu.java:195)
	at cratereloaded.S.a(CSGOMenu.java:112)
	at cratereloaded.W.a(CSGOTask.java:87)
	at cratereloaded.W.b(CSGOTask.java:11)
	at cratereloaded.X.run(CSGOTask.java:52)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
```

**Comment by imWillX** [comment]
Issue is likely fixed. Added checks around the code.
